
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░

env = HYPRCURSOR_THEME,Yuurei-Angel
env = HYPRCURSOR_SIZE,24

env = XCURSOR_THEME,Yuurei-Angel
env = XCURSOR_SIZE,24


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    # kb_layout = us
    # follow_mouse = 1
    # sensitivity = 0
    # force_no_accel = 0
    # accel_profile = flat 
    # numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }

}



# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}

# for window shallow similar to devour
misc {
    # enable_swallow = true
    # swallow_regex = (foot|kitty|allacritty|Alacritty|ghostty|Ghostty|org.wezfurlong.wezterm)
}

# Don't show update on first launch
ecosystem {
  # no_update_news = true
}

general {
    gaps_in = 4
    gaps_out = 6
    border_size = 1
    # col.active_border = rgba(2770C0FF) rgba(1E4C84FF) 45deg
    # col.inactive_border = rgba(A44185CC) rgba(012339CC) 45deg
    layout = dwindle
    resize_on_border = true
}


decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.95
    fullscreen_opacity = 1.0

    blur {
        enabled = yes
        size = 2
        passes = 4
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}
